name: Deploy to FTP

on:
  push:
    branches:
      - master # or the default branch of your repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the app
      - name: Build
        run: npx ng build --prod --base-href /WeatherApp/

      # List the contents of the build directory (for debugging)
      - name: List build directory contents
        run: ls -l dist/weatherapp

      # Deploy to sFTP
      - name: Deploy to sFTP
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/weatherapp
          remote: ${{ secrets.FTP_DIR }}
          host: ${{ secrets.FTP_ADDRESS }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.FTP_PORT }}
