name: Deploy to FTP

on:
  push:
    branches:
      - master # or the default branch of your repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the app
      - name: Build
        run: npm run build --prod

      # Deploy to FTP
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: ${{ secrets.FTP_ADDRESS }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: ${{ secrets.FTP_DIR }}
          local-dir: dist/weatherapp
