name: Deploy to FTP

on:
  push:
    branches:
      - master # or the default branch of your repository

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout
        uses: actions/checkout@v2

      # Install dependencies
      - name: Install Dependencies
        run: npm install

      # Build the app
      - name: Build
        run: npm run build --prod

      # Deploy to FTP
      - name: Deploy to sFTP
        uses: garygrossgarten/github-action-scp@release
        with:
          local: dist/weatherapp/*
          remote: /var/www/my_webapp__3/www/
          host: demos.pixdev.ovh
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 41337
